name: 🐞 Bug Report
description: Create a report to help us improve
title: "[Bug]: <title>"
labels: ["bug"]
assignees:
  - leonardk11
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of XOA Python API are you running?
      options:
        - 1.0.8 (Default)
        - 1.0.7
        - 1.0.6
        - 1.0.5
        - 1.0.4
        - 1.0.3
        - 1.0.2
        - 1.0.1
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: What version of Python are you seeing the problem on?
      multiple: true
      options:
        - Python 3.10
        - Python 3.9
        - Python 3.8
        - Python 3.7
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. With this config...
        2. Run '...'
        3. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
