name: 🐞 Bug Report
description: Create a report to help us improve
title: "[🐞Bug]: "
labels: ["bug"]
assignees:
  - leonardk11
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Your name and how can we get in touch with you if we need more info?
      placeholder: ex. Your Name, email@example.com
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: version
    attributes:
      label: XOA Python API Version
      description: What version of XOA Python API (xoa-driver) are you running?
      options:
        - 1.0.8 (Default)
        - 1.0.7
        - 1.0.6
        - 1.0.5
        - 1.0.4
        - 1.0.3
        - 1.0.2
        - 1.0.1
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you seeing the problem on?
      placeholder: "Python 3.10.5"
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Which operating system are you seeing the problem on?
      placeholder: "macOS 12.4"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. With this config...
        2. Run '...'
        3. See error...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
