name: 🧐 Question
description: Ask us a question about XOA Python API
title: "[🧐 Question]: "
labels: ["question"]
assignees:
  - leonardk11
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Your name and how can we get in touch with you if we need more info?
      placeholder: ex. Your Name, email@example.com
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: version
    attributes:
      label: XOA Python API Version
      description: What version of XOA Python API (xoa-driver) are you running?
      options:
        - 1.0.8 (Default)
        - 1.0.7
        - 1.0.6
        - 1.0.5
        - 1.0.4
        - 1.0.3
        - 1.0.2
        - 1.0.1
    validations:
      required: true
  - type: textarea
    id: question-description
    attributes:
      label: Describe your question.
      description: A clear and concise description of your question. Ex. How do I [...]?
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false